### ISSUE TITLE
Setup a continuous integration

### ISSUE THREAD

**Issue by wolframkriesing** [SengitU/kavun#5]
Make sure that every commit gets validated by running their tests.
How? There are many ways, figure out which one you like and what you need.

**Comment by SengitU** [comment]
It's a great idea to have a CI up and running. I know there are some alternatives like travis or netlify.

I will evaluate and apply them.

**Comment by SengitU** [comment]
I have added TravisCI to the project.

**Comment by wolframkriesing** [comment]
Awesome!

cu
Wolfram

Ugurcan <notifications@github.com> schrieb am Fr., 20. Apr. 2018, 15:28:
